PATH = 'ex1.txt'

N_DAYS = 80
TIMER_AFTER_SPAWN = 6
TIMER_AFTER_BIRTH = 8

def seafish_spawned_by(timer, days_left):
	if timer + 1 > days_left:
		return 0

	days_left -= timer + 1

	count = 0
	while days_left >= 0:
		# count new seafish
		count += 1
		# count seafishes generated by the new one
		count += seafish_spawned_by(TIMER_AFTER_BIRTH, days_left)
		days_left -= TIMER_AFTER_SPAWN + 1

	return count


with open(PATH) as f:
	lines = [line.strip() for line in f.readlines()]

timers = lines[0].split(',')

final_count = 0
for timer_str in timers:
	timer = int(timer_str)

	# counting this seafish itself as 1
	final_count += 1 + seafish_spawned_by(timer, N_DAYS)

print(final_count)